export const ROLES = {
  OWNER: 'owner',
  ADMIN: 'admin',
  MANAGER: 'manager',
  MEMBER: 'member',
};

export const PERMISSIONS = {
  MANAGE_WORKSPACE: 'MANAGE_WORKSPACE',
  INVITE_MEMBERS: 'INVITE_MEMBERS',
  REMOVE_MEMBERS: 'REMOVE_MEMBERS',
  CREATE_PROJECT: 'CREATE_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',
  CREATE_TASK: 'CREATE_TASK',
  ASSIGN_TASK: 'ASSIGN_TASK',
  DELETE_TASK: 'DELETE_TASK',
  MANAGE_BILLING: 'MANAGE_BILLING',
};

const ROLE_PERMISSIONS = {
  [ROLES.OWNER]: [
    PERMISSIONS.MANAGE_WORKSPACE,
    PERMISSIONS.INVITE_MEMBERS,
    PERMISSIONS.REMOVE_MEMBERS,
    PERMISSIONS.CREATE_PROJECT,
    PERMISSIONS.DELETE_PROJECT,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.ASSIGN_TASK,
    PERMISSIONS.DELETE_TASK,
    PERMISSIONS.MANAGE_BILLING,
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.MANAGE_WORKSPACE,
    PERMISSIONS.INVITE_MEMBERS,
    PERMISSIONS.REMOVE_MEMBERS,
    PERMISSIONS.CREATE_PROJECT,
    PERMISSIONS.DELETE_PROJECT,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.ASSIGN_TASK,
    PERMISSIONS.DELETE_TASK,
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.CREATE_PROJECT,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.ASSIGN_TASK,
    PERMISSIONS.DELETE_TASK,
  ],
  [ROLES.MEMBER]: [
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.ASSIGN_TASK,
  ],
};

export const hasPermission = (userRole, permission) => {
  if (!userRole) return false;
  const role = userRole.toLowerCase();
  const permissions = ROLE_PERMISSIONS[role] || ROLE_PERMISSIONS[ROLES.MEMBER];
  return permissions.includes(permission);
};

export const canManageWorkspace = (role) => hasPermission(role, PERMISSIONS.MANAGE_WORKSPACE);
export const canCreateProject = (role) => hasPermission(role, PERMISSIONS.CREATE_PROJECT);
export const canDeleteProject = (role) => hasPermission(role, PERMISSIONS.DELETE_PROJECT);
export const canInviteMembers = (role) => hasPermission(role, PERMISSIONS.INVITE_MEMBERS);
